### ISSUE TITLE
Feature request: Possibility to collapse/expand nested properties

### ISSUE THREAD

**Issue by JLNNN** [Mermade/widdershins#110]
When using many nested properties, the API docs can become very hard to read - is it possible to add some kind of - and + to collapse and expand these properties and get rid of the many arrows `»`? Or is that something slate is responsible for?

![bildschirmfoto 2018-04-13 um 10 24 44](https://user-images.githubusercontent.com/1099235/38724779-8b344914-3f05-11e8-8f04-3fd1700e21f4.png)

Again, thanks for your great work!

**Comment by MikeRalphson** [comment]
Because we generate static html from the markdown with slate (or shins) it isn't easy to have collapsible sections. We may (see issue #107) add a way to limit the depth of the schemas output, but this is complicated if your schemas are a mix of inline objects and `$ref`s to other schemas. 

If you are looking for dynamic documentation, it may be worth looking at something like [ReDoc](https://github.com/rebilly/redoc) ?

**Comment by MikeRalphson** [comment]
Just to add that the html `<details>` tag is a possibility, though I don't believe it plays well with tables.

**Comment by JLNNN** [comment]
ReDoc is really nice in that case, thank you for answering 👍
