### ISSUE TITLE
How can List "tags" in exactly the order I created in Swagger

### ISSUE THREAD

**Issue by trangnnp-ibl** [Mermade/widdershins#145]
How can List "tags" in exactly the order I created in Swagger, not in alphabetical order.

example:
My "tags" name order in Swagger are: "A","D","C"
But after building by widdershin, "tags" name order are: "A","C","D"

I see the PetStore donot have this problem, but I donnot know how to fix it.
Help meeeeee
Thanks!

**Comment by MikeRalphson** [comment]
Hi @trangnnp-ibl - you've spotted what is basically a bug, but let me give you a quick explanation of why it is happening (which may help resolve it for you in the meantime) as well as a couple of alternative workarounds.

As you are probably aware, operations in OpenAPI can have more than one tag, but we don't want operations to appear more than once in the ToC even though that is driven by tags. Operations may also be 'tagless'. For that reason, the list of 'effective' tags is generated from the first tag in each operation's tags array, plus a 'default' tag if needed.

What is going wrong is that the effective tags are being built up in the order they're seen in the operations, and not respecting the order of the top-level tags array.

So, workarounds:

1. Move the operations around so your operation tagged with "D" is the second in the list (or the first one to use a tag which isn't "A")
2. Use the `tagGroups` feature of the `--environment` option to override the tags section. This is documented in the README (it was added in PR #136)

I hope to have this fixed in the next patch version.

**Comment by MikeRalphson** [comment]
Waiting on #107 to be tested.

**Comment by MikeRalphson** [comment]
Included in `v3.6.1` - apologies for the wait.
