### ISSUE TITLE
Split whole markdown page to multiple sub pages

### ISSUE THREAD

**Issue by toanstt** [Mermade/widdershins#235]
Any option to split big file to multiple smaller files

**Comment by MikeRalphson** [comment]
There is currently no option to do this.

This seems related to #82 - because Widdershins is designed to work with Slate/Shins which expect one input file containing everything which contributes to the ToC it's not likely to be a high priority.

There should be nothing stopping you splitting the output file into multiple files based on some header which already exists in the markdown or by adding some kind of tag to one of the templates.
